=== molsonkiko/align_isoforms/website/staticfiles/peptides/protein_json_schema.5bbd59d83e47.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "UniProt ID": {
            "type": "string"
        },
        "sequence": {
            "type": "string"
        },
        "Isoform UniProt IDs": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "isoform alignments": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "mass spec peptides": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "integer"
                    },
                    "sequence": {
                        "type": "string"
                    }
                },
                "required": [
                    "location",
                    "sequence"
                ]
            }
        }
    },
    "required": [
        "Isoform UniProt IDs",
        "UniProt ID",
        "isoform alignments",
        "mass spec peptides",
        "sequence"
    ]
}

=== molsonkiko/align_isoforms/protein_json_example.json
{
    "UniProt ID": "P56856",
    "sequence": "MSTTTCQVVAFLLSILGLAGCIAATGMDMWSTQDLYDNPVTSVFQYEGLWRSCVRQSSGFTECRPYFTILGLPAMLQAVRALMIVGIVLGAIGLLVSIFALKCIRIGSMEDSAKANMTLTSGIMFIVSGLCAIAGVSVFANMLVTNFWMSTANMYTGMGGMVQTVQTRYTFGAALFVGWVAGGLTLIGGVMMCIACRGLAPEETNYKAVSYHASGHSVAYKPGGFKASTGFGSNTKNKKIYDGGARTEDEVQSYPSKHDYV",
    "Isoform UniProt IDs": [
        "P56856-2"
    ],
    "isoform alignments": [
        "CLUSTAL O(1.2.4) multiple sequence alignment\n\n\nP56856        MSTTTCQVVAFLLSILGLAGCIAATGMDMWSTQDLYDNPVTSVFQYEGLWRSCVRQSSGF\t60\nP56856-2      MAVTACQGLGFVVSLIGIAGIIAATCMDQWSTQDLYNNPVTAVFNYQGLWRSCVRESSGF\t60\n              *:.*:** :.*::*::*:** **** ** *******:****:**:*:********:****\n\nP56856        TECRPYFTILGLPAMLQAVRALMIVGIVLGAIGLLVSIFALKCIRIGSMEDSAKANMTLT\t120\nP56856-2      TECRGYFTLLGLPAMLQAVRALMIVGIVLGAIGLLVSIFALKCIRIGSMEDSAKANMTLT\t120\n              **** ***:***************************************************\n\nP56856        SGIMFIVSGLCAIAGVSVFANMLVTNFWMSTANMYTGMGGMVQTVQTRYTFGAALFVGWV\t180\nP56856-2      SGIMFIVSGLCAIAGVSVFANMLVTNFWMSTANMYTGMGGMVQTVQTRYTFGAALFVGWV\t180\n              ************************************************************\n\nP56856        AGGLTLIGGVMMCIACRGLAPEETNYKAVSYHASGHSVAYKPGGFKASTGFGSNTKNKKI\t240\nP56856-2      AGGLTLIGGVMMCIACRGLAPEETNYKAVSYHASGHSVAYKPGGFKASTGFGSNTKNKKI\t240\n              ************************************************************\n\nP56856        YDGGARTEDEVQSYPSKHDYV\t261\nP56856-2      YDGGARTEDEVQSYPSKHDYV\t261\n              *********************\n"
    ],
    "mass spec peptides": [
        {
            "location": 40,
            "sequence": "TSVFQYEGLWR"
        }
    ]
}
